{
 "title": "New dashboard",
 "time": { "from": "2009-12-14T00:31:15.542Z", "to": "2022-06-24T00:00:00.000Z" },
 "panels": [
  {
   "title": "Quantidade total de reclamações por data de vigência",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  \r\n    DATAVIGENCIA as \"time\",\r\n    SUM(QUANTIDADE_TOTAL_DE_RECLAMAES) AS QUANTIDADE_TOTAL_DE_RECLAMAES\r\nFROM\r\n    DW.FT_INDICE_RECLAMACAO\r\nGROUP BY \r\n    DATAVIGENCIA\r\nORDER BY  \r\n    DATAVIGENCIA;"
    }
   ]
  },
  {
   "title": "Soma de valores das tarifas por data de vigência a partir de 2010",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATAVIGENCIA as \"time\",\r\n    SUM(VALORMAXIMO) AS VALOR_TARIFA_MAXIMO\r\nFROM\r\n    DW.FT_INDICE_RECLAMACAO\r\nWHERE\r\n    DATAVIGENCIA > \"2010-01-01\"\r\nGROUP BY \r\n    DATAVIGENCIA\r\nORDER BY \r\n    DATAVIGENCIA;"
    }
   ]
  },
  {
   "title": "Quantidade de reclamações por trimestre no ano de 2021",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    CAST(SUBSTRING(TRIM(TRIMESTRE),1,1) AS FLOAT) as \"time\",\n    SUM(QUANTIDADE_DE_RECLAMAES_REGULADAS_PROCEDENTES) AS QUANTIDADE_DE_RECLAMAES_REGULADAS_PROCEDENTES,\n    SUM(QUANTIDADE_DE_RECLAMAES_REGULADAS_OUTRAS) AS QUANTIDADE_DE_RECLAMAES_REGULADAS_OUTRAS,\n    SUM(QUANTIDADE_DE_RECLAMAES_NO_REGULADAS) AS QUANTIDADE_DE_RECLAMAES_NO_REGULADAS\nFROM\n    DW.FT_INDICE_RECLAMACAO\nWHERE\n    ANO = 2021\nGROUP BY \n    SUBSTRING(TRIM(TRIMESTRE),1,1)\nORDER BY  \n    SUBSTRING(TRIM(TRIMESTRE),1,1);"
    }
   ]
  }
 ]
}